### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by jbschiratti** [choldgraf/download#8]
I am using `download` library to download (and unzip) the following file: `http://epileptologie-bonn.de/cms/upload/workgroup/lehnertz/S.zip`.

With the default timeout parameter in `_fetch_file`, I get the following error: (I executed the function several times and got the error each time)

```
Traceback (most recent call last):
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\site-packages\download-0.3.3-py3.6.egg\download\download.py", line 181, in _fetch_file
    u = urllib.request.urlopen(url, timeout=timeout)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\urllib\request.py", line 1321, in do_open
    r = h.getresponse()
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0e7d9eacbf74>", line 1, in <module>
    download_bonn_ieeg(path='C:/Personnel')
  File "C:\Users\Jean-Baptiste\PycharmProjects\mne-features\mne_features\examples_utils\utils_seizure.py", line 25, in download_bonn_ieeg
    kind='zip', replace=True, verbose=True)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\site-packages\download-0.3.3-py3.6.egg\download\download.py", line 89, in download
    _fetch_file(download_url, path_temp_file, verbose=verbose)
  File "C:\Users\Jean-Baptiste\Anaconda3\lib\site-packages\download-0.3.3-py3.6.egg\download\download.py", line 229, in _fetch_file
    ' Dataset fetching aborted.\nError: %s' % (url, ee))
RuntimeError: Error while fetching file http://epileptologie-bonn.de/cms/upload/workgroup/lehnertz/N.zip. Dataset fetching aborted.
Error: timed out
```

Setting `timeout=100` in `_fetch_file` did not trigger an error and allowed me to download the file.

Would it be possible to have a `timeout` parameter in the `download` function ? It's an easy PR.

**Comment by choldgraf** [comment]
for sure - do you have a moment to make a PR? otherwise I can try to get to it when I have a moment

**Comment by jbschiratti** [comment]
Thank you. Sure, I'll make a PR.

**Comment by choldgraf** [comment]
Thanks :-)

**Comment by jbschiratti** [comment]
See #9.
